GET http://localhost:3000/usuario

###

POST http://localhost:3000/usuario
Content-Type: application/json

{
    "nome": "Gabriel",
    "email": "gabi33@gmail.com",
    "telefone": "(48) 9 9999-9999",
    "senha": "432"
}

###

DELETE http://localhost:3000/usuario/2

###

GET http://localhost:3000/produto

###

POST http://localhost:3000/produto
Content-Type: application/json

{
  "nome_produto": "Smartphone Motorola Edge 60 Fusion 5G - 256GB 16GB (8GB RAM + 8GB Boost) 50MP Sony AI Camera IP68 NFC - Cinza Vegan Leather",
  "url": "https://http2.mlstatic.com/D_NQ_NP_2X_857703-MLA97091350851_112025-F.webp",
  "descricao": "Lançabra de 520aloeira.",
  "direcionamento": "https://www.mercadolivre.com.br/smartphone-motorola-edge-60-fusion-5g-256gb-16gb-8gb-ram8gb-ram-boost-50mp-sony-ai-camera-ip68-nfc-cinza-vegan-leather/p/MLB47245501"
}