GET http://localhost:3000/usuario

###

POST http://localhost:3000/usuario
Content-Type: application/json

{
    "nome": "Gabriel",
    "email": "gabi33@gmail.com",
    "telefone": "(48) 9 9999-9999",
    "senha": "42132"
}

###

DELETE http://localhost:3000/usuario/2